# João Pedro Bastos Fernandes

### Verbo GET – listar todos
GET http://localhost:8000/funcionario/ HTTP/1.1
### Verbo GET – listar um
GET http://localhost:8000/funcionario/10 HTTP/1.1
### Verbo POST – adicionar
POST http://127.0.0.1:8000/funcionario/ HTTP/1.1
content-type: application/json

{
    "nome" : "João Pedro Bastos Fernandes",
    "matricula" : "123456",
    "cpf" : "1",
    "telefone" : "49991757242",
    "grupo" : 1,
    "senha" : "teste@123"
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/funcionario/1 HTTP/1.1
content-type: application/json

{
    "nome" : "João Pedro Bastos Fernandes",
    "matricula" : "123456",
    "cpf" : "10051205955",
    "telefone" : "49991757242",
    "grupo" : 1,
    "senha" : "teste@gmail.com"
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/funcionario/1 HTTP/1.1
